export const movie = {
  adult: false,
  backdrop_path: '/h8gHn0OzBoaefsYseUByqsmEDMY.jpg',
  belongs_to_collection: {
    id: 404609,
    name: 'John Wick - Colección',
    poster_path: '/ysIo1GKl7xLDBjEbyzmYAeiZMEE.jpg',
    backdrop_path: '/fSwYa5q2xRkBoOOjueLpkLf3N1m.jpg'
  },
  budget: 90000000,
  genres: [{ id: 28, name: 'Acción' }, { id: 53, name: 'Suspense' }, { id: 80, name: 'Crimen' }],
  homepage: '',
  id: 603692,
  imdb_id: 'tt10366206',
  original_language: 'en',
  original_title: 'John Wick: Chapter 4',
  overview: 'John Wick descubre un camino para derrotar a La Mesa. Pero antes de poder ganar su libertad, Wick deberá enfrentarse a un nuevo enemigo con poderosas alianzas en todo el mundo; y contra las fuerzas que convierten a viejos amigos en enemigos.',
  popularity: 4071.868,
  poster_path: '/gh2bmprLtUQ8oXCSluzfqaicyrm.jpg',
  production_companies: [{ id: 3528, logo_path: '/cCzCClIzIh81Fa79hpW5nXoUsHK.png', name: 'Thunder Road', origin_country: 'US' }, { id: 23008, logo_path: '/5SarYupipdiejsEqUkwu1SpYfru.png', name: '87Eleven', origin_country: 'US' }, { id: 491, logo_path: '/5LvDUt3KmvRnXQ4NrdWJYHeuA8J.png', name: 'Summit Entertainment', origin_country: 'US' }, { id: 264, logo_path: '/fA90qwUKgPhMONqtwY60GaHRyrW.png', name: 'Studio Babelsberg', origin_country: 'DE' }],
  production_countries: [{ iso_3166_1: 'DE', name: 'Germany' }, { iso_3166_1: 'US', name: 'United States of America' }],
  release_date: '2023-03-22',
  revenue: 431769198,
  runtime: 170,
  spoken_languages: [{ english_name: 'Arabic', iso_639_1: 'ar', name: 'العربية' }, { english_name: 'Cantonese', iso_639_1: 'cn', name: '广州话 / 廣州話' }, { english_name: 'English', iso_639_1: 'en', name: 'English' }, { english_name: 'French', iso_639_1: 'fr', name: 'Français' }, { english_name: 'German', iso_639_1: 'de', name: 'Deutsch' }, { english_name: 'Japanese', iso_639_1: 'ja', name: '日本語' }, { english_name: 'Latin', iso_639_1: 'la', name: 'Latin' }, { english_name: 'Russian', iso_639_1: 'ru', name: 'Pусский' }, { english_name: 'Spanish', iso_639_1: 'es', name: 'Español' }],
  status: 'Released',
  tagline: 'Sin vuelta atrás. Una salida.',
  title: 'John Wick 4',
  video: false,
  vote_average: 7.95,
  vote_count: 2783
}
